---
- hosts: Windows_group
  gather_facts: no
  vars:
    win_update_categories:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
        - UpdateRollups

  tasks:
  # Check if there are missing Critical and Security Updates
    - block:
        - name: Checking for Available Windows Updates
          win_updates:
            category_names: "{{ win_update_categories }}"
            state: searched
          register: available_updates
        - debug:
          # output the format in a pretty manner; requires ANSIBLE_STDOUT_CALLBACK=debug environment variable to be set
            msg: |
              {{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available.

              {% for key, value in available_updates.updates.iteritems() %}
                - {{ value.title }}
              {% endfor %}



        - name: Unzip
          win_dsc:
            resource_name: File
            DestinationPath: C:\Temp\frank
            Attributes: # can also be a comma separated string, e.g. 'Hidden, System'
            - ReadOnly 
            - System
            Ensure: Present
            Type: Directory


        - name: Create Interactive User
          win_user:
            name : Interactive-admin
            Password : RedHat1!
            state: present
            groups:
              - Administrators
            
       # - name: Add 127.0.0.1 as an A record for localhost
       #   win_hosts:
       #     state: present
       #     canonical_name: ansible
       #     ip_address: 168.1.95.190
            
        - name: Change power plan to high performance
          win_power_plan:
            name: high performance  
            
            
        - name: Enable firewall for Domain, Public and Private profiles
          win_firewall:
            state: disabled
            profiles:
            - Domain
            - Private
            - Public
          tags: disabled_firewall    


        - name: Download earthrise.jpg to specified path
          win_get_url:
            url: https://specials-images.forbesimg.com/imageserve/5d3dc05bf1176b000897d897/960x0.jpg?fit=scale
            dest: C:\Temp\earthrise.jpg

        - name: Add or update registry path MyCompany, with dword entry 'hello', and containing 1337 as the decimal value
          win_regedit:
            path: HKCU:\Software\MyCompany
            name: hello
            data: 1337
            type: dword
